services:
  cloudflare-ddns:
    image: ddns
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      WEB_PORT: "8070"
    ports:
      - 8070:8070
    restart: unless-stopped
    command: ./app

