services:
  cloudflare-ddns:
    image: ddns
    build:
      context: .
      dockerfile: ./Dockerfile
    network_mode: 'host'
    restart: unless-stopped
    # ports:
    #   - '8070:8070'
    command: python app.py

