services:
  cloudflare-ddns:
    image: ddns
    build:
      context: .
      dockerfile: ./Dockerfile
    network_mode: 'host'
    environment:
      WEB_PORT: "8070"
    restart: unless-stopped
    command: ./app

